cmake_minimum_required(VERSION 3.20)

find_program(CCACHE_PROGRAM ccache REQUIRED)

if(CCACHE_PROGRAM AND NOT ${CICD_SYSTEM})
  set_property(GLOBAL PROPERTY RULE_LAUNCH_COMPILE "${CCACHE_PROGRAM}")
  set(CMAKE_C_COMPILER_LAUNCHER "ccache")
  set(CMAKE_CXX_COMPILER_LAUNCHER "ccache")
endif()
