name: 'Build Pipeline'

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build_macos:
    name: Build on Mac
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        brew install check
        brew install pkg-config
        brew install gmp

    - name: Build with Make & launch tests
      working-directory: ${{github.workspace}}/docker
      run: |
        chmod +x test_s21_decimal_light.sh
        ./test_s21_decimal_light.sh
    
  build_docker:
    name: Build on Docker Container (Apline Linux)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker container & run it
      working-directory: ${{github.workspace}}/docker
      run: |
        chmod +x run_daemon.sh
        ./run_daemon.sh